# Generated by Django 5.2.3 on 2025-06-24 05:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='regsiter',
            fields=[
                ('A_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(3, 'Username must be at least 3 characters')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(8, 'Password must be at least 8 characters'), django.core.validators.RegexValidator(message='Password must contain letters and numbers', regex='^(?=.*[A-Za-z])(?=.*\\d).+$')])),
            ],
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
